version: "3.7"
services:
  postgres:
    container_name: remix-nestjs
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # redis:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  # mongodb:
  #   image: mongo
  #   ports:
  #     - '27017:27017'
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
